### ISSUE TITLE
Pease add some docs about setup project

### ISSUE THREAD

**Issue by gustawdaniel** [buaya91/scalajs-snake#2]
I installed `scala` and `sbt` on ubuntu

I typed `sbt compile` and got some output and finally error

```

...

[warn] 	[FAILED     ] com.typesafe.sbt#sbt-native-packager;1.2.0-M8!sbt-native-packager.jar: Unexpected end of file from server (131671ms)
[warn] 	[FAILED     ] com.typesafe.sbt#sbt-native-packager;1.2.0-M8!sbt-native-packager.jar: Unexpected end of file from server (131671ms)
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.2.0-M8/jars/sbt-native-packager.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbt#sbt-native-packager;1.2.0-M8!sbt-native-packager.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: com.typesafe.sbt#sbt-native-packager;1.2.0-M8!sbt-native-packager.jar
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: download failed: com.typesafe.sbt#sbt-native-packager;1.2.0-M8!sbt-native-packager.jar
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
[error] Not a valid command: compile (similar: completions)
[error] compile
[error]        ^
```

So how to setup this project?

**Comment by gustawdaniel** [comment]
I would like to get some info about differences between this project and vmunier/play-scalajs.g8

I have link to this repo from blog:

> https://www.cakesolutions.net/teamblogs/how-does-multiplayer-game-sync-their-state-part-2

I want to learn how to create multiplayer game, but I do not know which source code will be better example?

**Comment by qingwei91** [comment]
@gustawdaniel 

For the 1st error, I am not sure what is happening, maybe you can try to upgrade `sbt-native-packager` plugin to latest version which is `1.3.3`

I forked `vmunier/play-scalajs.g8` just to get some default setup, so the upstream does not contain any code related to game

**Comment by gustawdaniel** [comment]
I changed version file `project/plugins.sbt`

    addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.3")

Now error show that downloading failed again for this version.

```
[info] Loading project definition from /home/daniel/exp/scalajs-snake/project
[warn] 	[FAILED     ] com.typesafe.sbt#sbt-native-packager;1.3.3!sbt-native-packager.jar(doc): Unexpected end of file from server (122893ms)
[warn] 	[FAILED     ] com.typesafe.sbt#sbt-native-packager;1.3.3!sbt-native-packager.jar(src): Unexpected end of file from server (122998ms)
[warn] 	[FAILED     ] com.typesafe.sbt#sbt-native-packager;1.3.3!sbt-native-packager.jar(doc):  (0ms)
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.3.3/docs/sbt-native-packager-javadoc.jar
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.3.3/docs/sbt-native-packager-javadoc.jar
[warn] ==== local: tried
[warn]   /home/daniel/.ivy2/local/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.3.3/docs/sbt-native-packager-javadoc.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.10_0.13/1.3.3/sbt-native-packager-1.3.3-javadoc.jar
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/daniel/.sbt/preloaded/com.typesafe.sbt/sbt-native-packager/1.3.3/docs/sbt-native-packager-javadoc.jar
[warn] ==== local-preloaded: tried
[warn]   file:////home/daniel/.sbt/preloaded/com/typesafe/sbt/sbt-native-packager_2.10_0.13/1.3.3/sbt-native-packager-1.3.3-javadoc.jar
[warn] ==== Typesafe repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-native-packager_2.10_0.13/1.3.3/sbt-native-packager-1.3.3-javadoc.jar
[warn] ==== heroku-sbt-plugin-releases: tried
[warn]   https://dl.bintray.com/heroku/sbt-plugins/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.3.3/docs/sbt-native-packager-javadoc.jar
[warn] 	[FAILED     ] com.typesafe.sbt#sbt-native-packager;1.3.3!sbt-native-packager.jar(src):  (0ms)
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.3.3/srcs/sbt-native-packager-sources.jar
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.3.3/srcs/sbt-native-packager-sources.jar
[warn] ==== local: tried
[warn]   /home/daniel/.ivy2/local/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.3.3/srcs/sbt-native-packager-sources.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.10_0.13/1.3.3/sbt-native-packager-1.3.3-sources.jar
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/daniel/.sbt/preloaded/com.typesafe.sbt/sbt-native-packager/1.3.3/srcs/sbt-native-packager-sources.jar
[warn] ==== local-preloaded: tried
[warn]   file:////home/daniel/.sbt/preloaded/com/typesafe/sbt/sbt-native-packager_2.10_0.13/1.3.3/sbt-native-packager-1.3.3-sources.jar
[warn] ==== Typesafe repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-native-packager_2.10_0.13/1.3.3/sbt-native-packager-1.3.3-sources.jar
[warn] ==== heroku-sbt-plugin-releases: tried
[warn]   https://dl.bintray.com/heroku/sbt-plugins/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.3.3/srcs/sbt-native-packager-sources.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbt#sbt-native-packager;1.3.3!sbt-native-packager.jar(doc)
[warn] 	:: com.typesafe.sbt#sbt-native-packager;1.3.3!sbt-native-packager.jar(src)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: com.typesafe.sbt#sbt-native-packager;1.3.3!sbt-native-packager.jar(doc)
download failed: com.typesafe.sbt#sbt-native-packager;1.3.3!sbt-native-packager.jar(src)
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbtproject/plugins.sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: download failed: com.typesafe.sbt#sbt-native-packager;1.3.3!sbt-native-packager.jar(doc)
[error] download failed: com.typesafe.sbt#sbt-native-packager;1.3.3!sbt-native-packager.jar(src)
```
I come back to some of first commits and tried to run this by command

    sbt run

| Commit                                   | Status                                             |
|------------------------------------------|----------------------------------------------------|
| 725c23acbf6027a89121bc87ee7fca4636402670 | [error] (root/compile:run) No main class detected. |
| 7a97bc0d7310fffc9b48e72c940716448bf045cf | [error] (root/compile:run) No main class detected.  |
| 39874c6bee9325472560a91640f5f977aaa5c2ec | [error] (root/compile:run) No main class detected. |
| 634c73dd4a8cca2ba47a02bdaa2ad4dab94d3796 | [error] (root/compile:run) No main class detected. |

```
[info] Loading project definition from /home/daniel/exp/scalajs-snake/project
[info] Set current project to root (in build file:/home/daniel/exp/scalajs-snake/)
java.lang.RuntimeException: No main class detected.
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last root/compile:run for the full output.
[error] (root/compile:run) No main class detected.
[error] Total time: 0 s, completed 2018-03-22 17:01:07
```

I thougth that travis can help but I do not see file `ci/checksourcemaps.sh` from 17 line of `.travis.yml` and do not know how to debug this.

**Comment by qingwei91** [comment]
@gustawdaniel Hey sorry for the confusion on travis, I am not using it, removed now.

I cannot reproduce your problem with dependency, I wonder if it's related to your environment, eg. network?

**Comment by gustawdaniel** [comment]
It is possible. Anyway thanks for your responses. :)
